spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  servlet:
    context-path: /productmgmt/rest

management:
  endpoints:
    web:
      exposure:
        include: "*"